spring:
  data:
    mongodb:
      host: '${MONGO_HOST:localhost}'
      username: '${MONGO_INITDB_ROOT_USERNAME}'
      authentication-database: admin
      password: '${MONGO_INITDB_ROOT_PASSWORD}'
      port: 27017
      database: '${MONGO_DB:BookStore}'
uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo-mongodb-0.mongo-mongodb-headless.mongodb.svc:27017,mongo-mongodb-1.mongo-mongodb-headless.mongodb.svc:27017,mongo-mongodb-2.mongo-mongodb-headless.mongodb.svc:27017/test
logging:
  level:
    org:
      springframework:
        data.mongodb: INFO
        boot.autoconfigure.mongo: INFO
    com.mongodb.client: INFO

  cloud:
    kubernetes:
      discovery:
        register: true

      config:
        enabled: true
        sources:
          - namespace: default
            name: mongodb-configmap
      reload:
        enabled: true
        mode: polling
        period: 1000